export const SUPABASE_URL = "https://uyghrhjitzableltcfeu.supabase.co";
export const SUPABASE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV5Z2hyaGppdHphYmxlbHRjZmV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg4NDI4NzQsImV4cCI6MjA5NDQxODg3NH0.mRjE6BbEPmukdXrpfI3GpmHkNoYxab4SPSsymFTk5yU";
